server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: getnet-service
          uri: hhtp://localhost:8080/
          predicates:
           - Path=/getnet/**
